### PR TITLE
Automatically upload .framework when tagging

### PR DESCRIPTION
**Pull request by RuiAAPeres**

### CODE REVIEW

**Comment by dmcrodrigues** [comment]
Super cool and a big help ✨

**Comment by neilpa** [comment]
Damn, wish I had known this was possible. Doing this by hand was annoying.

**Comment by RuiAAPeres** [comment]
All credits to @dmcrodrigues for doing the same on [Velhotes/Vinyl](https://github.com/Velhotes/Vinyl).

**Comment by ikesyo** [comment]
I think we don't need the `before_install:` step anymore. Let's use newer Carthage preinstalled in Travis.

**Comment by RuiAAPeres** [comment]
@ikesyo if you are happy with the change, please merge. 💃

**Comment by ikesyo** [comment]
Looks good 👍

**Pull request merged**
