### PR TITLE
Added UIKit extensions 

### PR DESCRIPTION
**Pull request by avalanched**

### CODE REVIEW

**Comment by neilpa** [comment]
These are great! Thanks for the PR.

I can cut a new release with these if you'd like. Otherwise I was waiting for the RAC 4 alpha 2.

**Comment by avalanched** [comment]
waiting for alpha 2 is just fine for me. I will try to add some more the coming days.

**Comment by neilpa** [comment]
> I will try to add some more the coming days.

:smile:

**Comment by bjarkehs** [comment]
Out of curiosity: How do the retain cycle tests work?
Nvm, I just realized it was all in the tearDown. :+1:

**Comment by avalanched** [comment]
@bjarkehs in the tearDown you check if the object is successfully deallocated, there was a retain cycle issue in a previous build when binding a property, this was fixed in https://github.com/neilpa/Rex/issues/28

**Comment by bjarkehs** [comment]
@avalanched Yeah, I edited my own comment a few seconds before your response. Had not expected anyone to respond this quickly. Anyway, thanks for the added properties :smile:

**Pull request merged**
