### PR TITLE
Implement `rex_selectedSegmentIndex` for UISegmentedControl

### PR DESCRIPTION
**Pull request by iv-mexx**
Title says it all

### CODE REVIEW

**Comment by iv-mexx** [comment]
Hm, the first CI fails were because I've added `UISegmentedControl` to all targets instead of only to the iOS target. I've already fixed that.

But now, it seems to still fail for the tvOS target: 

> -> Rex (0.10.0)
>     - ERROR | [tvOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
>     - ERROR | [tvOS] xcodebuild:  /Users/travis/build/neilpa/Rex/Source/UIKit/UISegmentedControl.swift:16:21: error: use of unresolved identifier 'rex_controlEvents'> 

even though the `UISegmentedControl.swift` is not added to the tvOS target anymore 😕

**Comment by iv-mexx** [comment]
Oh nevermind, i guess `UISegmentedControl.swift` needs to be explicitly excluded for the tvOS target in the Podspec.

**Comment by neilpa** [comment]
> Oh nevermind, i guess UISegmentedControl.swift needs to be explicitly excluded for the tvOS target in the Podspec.

I've hit this problem a couple times too. One of the reasons I'm not a fan of pods since you have multiple project definitions.

**Comment by neilpa** [comment]
@iv-mexx I invited you as a collaborator to the repo. Feel free to review and merge PRs since I'm not as on top of them these days.

**Comment by iv-mexx** [comment]
@neilpa Cool, thanks 😃 🎉

**Pull request merged**
